name: Deploy Produção FrontEnd

on:
  push:
    branches:
     - "main"

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
     with:
      fetch-depth: 0
   
   - name: Install Node.js
     uses: actions/setup-node@v3
     with:
      node-version: '18.x'
   
   - name: Install npm dependencies
     run: npm install 
   
   - name: Run build task
     run: npm run build

   - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@ece05a22752e524363164bfb2f69a5ba4f8ded0d
     uses: easingthemes/ssh-deploy@v5.1.0
     with:
          # Private key part of an SSH key pair
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # Remote host
      REMOTE_HOST:  ${{ secrets.REMOTE_HOST }}
      # Remote user
      REMOTE_USER:  ${{ secrets.REMOTE_USER }}
      # Remote port
      REMOTE_PORT:  ${{ secrets.REMOTE_PORT }}
      # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
      SOURCE: "/" 
      # Target directory
      TARGET: ~/apps/app-dietinha # optional, default is 
      # paths to exclude separated by `,`, ie: `/dist/, /node_modules/`
      EXCLUDE: '/src/, /js/node/, /node_modules/, /.vscode/, /.github/, /@types/, /.gitignore, /.babelrc, /rollup.config.js, /vitest.config.ts'  
      # Script to run on host machine before rsync
      #SCRIPT_BEFORE: # optional, default is 
      # If not an empty string, the action will fail if the before script fails. Note: The string 'false' will be treated as true
      #SCRIPT_BEFORE_REQUIRED: # optional, default is 
      # Script to run on host machine after rsync
      #SCRIPT_AFTER: # optional, default is 
      # If not an empty string, the action will fail if the after script fails. Note: The string 'false' will be treated as true
      #SCRIPT_AFTER_REQUIRED: # optional, default is 
